In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("D:\ML Verzeo\CarPrice_Assignment.csv")

In [3]:
df

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [4]:
df.head(5)

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [6]:
len(df)

205

In [7]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [8]:
df['price'].loc[df['fueltype']=='diesel'].mean()

15838.15

In [9]:
df['price'].loc[df['fueltype']=='gas'].mean()

12999.7982

In [10]:
df['price'].loc[df['doornumber']=='two'].mean()

12989.924077777776

In [11]:
df['price'].loc[df['doornumber']=='four'].mean()

13501.152173913044

In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
scaler=StandardScaler()

In [14]:
scaler.fit(a)

StandardScaler()

In [15]:
scaler.mean_

array([4., 5., 6.])

In [16]:
scaler.var_

array([6., 6., 6.])

In [17]:
df['aspiration'].value_counts()

std      168
turbo     37
Name: aspiration, dtype: int64

In [18]:
df['carbody'].value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: carbody, dtype: int64

In [19]:
df['drivewheel'].value_counts()

fwd    120
rwd     76
4wd      9
Name: drivewheel, dtype: int64

In [20]:
df['enginelocation'].value_counts()

front    202
rear       3
Name: enginelocation, dtype: int64

In [21]:
df['enginetype'].value_counts()

ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: enginetype, dtype: int64

In [22]:
df['fuelsystem'].value_counts()

mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuelsystem, dtype: int64

In [23]:
columns_to_be_dropped=['car_ID','symboling','CarName']

In [24]:
df.drop(columns=columns_to_be_dropped,inplace=True)

In [25]:
df

fueltype aspiration doornumber      carbody drivewheel enginelocation  \
0        gas        std        two  convertible        rwd          front   
1        gas        std        two  convertible        rwd          front   
2        gas        std        two    hatchback        rwd          front   
3        gas        std       four        sedan        fwd          front   
4        gas        std       four        sedan        4wd          front   
..       ...        ...        ...          ...        ...            ...   
200      gas        std       four        sedan        rwd          front   
201      gas      turbo       four        sedan        rwd          front   
202      gas        std       four        sedan        rwd          front   
203   diesel      turbo       four        sedan        rwd          front   
204      gas      turbo       four        sedan        rwd          front   

     wheelbase  carlength  carwidth  carheight  ...  enginesize fuelsystem  \
0         88.6      168.8      64.1       48.8  ...         130       mpfi   
1         88.6      168.8      64.1       48.8  ...         130       mpfi   
2         94.5      171.2      65.5       52.4  ...         152       mpfi   
3         99.8      176.6      66.2       54.3  ...         109       mpfi   
4         99.4      176.6      66.4       54.3  ...         136       mpfi   
..         ...        ...       ...        ...  ...         ...        ...   
200      109.1      188.8      68.9       55.5  ...         141       mpfi   
201      109.1      188.8      68.8       55.5  ...         141       mpfi   
202      109.1      188.8      68.9       55.5  ...         173       mpfi   
203      109.1      188.8      68.9       55.5  ...         145        idi   
204      109.1      188.8      68.9       55.5  ...         141       mpfi   

    boreratio  stroke compressionratio  horsepower  peakrpm  citympg  \
0        3.47    2.68              9.0         111     5000       21   
1        3.47    2.68              9.0         111     5000       21   
2        2.68    3.47              9.0         154     5000       19   
3        3.19    3.40             10.0         102     5500       24   
4        3.19    3.40              8.0         115     5500       18   
..        ...     ...              ...         ...      ...      ...   
200      3.78    3.15              9.5         114     5400       23   
201      3.78    3.15              8.7         160     5300       19   
202      3.58    2.87              8.8         134     5500       18   
203      3.01    3.40             23.0         106     4800       26   
204      3.78    3.15              9.5         114     5400       19   

     highwaympg    price  
0            27  13495.0  
1            27  16500.0  
2            26  16500.0  
3            30  13950.0  
4            22  17450.0  
..          ...      ...  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0  

[205 rows x 23 columns]

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   fueltype          205 non-null    object 
 1   aspiration        205 non-null    object 
 2   doornumber        205 non-null    object 
 3   carbody           205 non-null    object 
 4   drivewheel        205 non-null    object 
 5   enginelocation    205 non-null    object 
 6   wheelbase         205 non-null    float64
 7   carlength         205 non-null    float64
 8   carwidth          205 non-null    float64
 9   carheight         205 non-null    float64
 10  curbweight        205 non-null    int64  
 11  enginetype        205 non-null    object 
 12  cylindernumber    205 non-null    object 
 13  enginesize        205 non-null    int64  
 14  fuelsystem        205 non-null    object 
 15  boreratio         205 non-null    float64
 16  stroke            205 non-null    float64
 1

In [27]:
labelencoder=LabelEncoder()

In [28]:
for column in df.columns:
    if df[column].dtype=='object':
        labelencoder.fit(df[column].values)
        df[column]=labelencoder.transform(df[column].values)
        

In [29]:
df

fueltype  aspiration  doornumber  carbody  drivewheel  enginelocation  \
0           1           0           1        0           2               0   
1           1           0           1        0           2               0   
2           1           0           1        2           2               0   
3           1           0           0        3           1               0   
4           1           0           0        3           0               0   
..        ...         ...         ...      ...         ...             ...   
200         1           0           0        3           2               0   
201         1           1           0        3           2               0   
202         1           0           0        3           2               0   
203         0           1           0        3           2               0   
204         1           1           0        3           2               0   

     wheelbase  carlength  carwidth  carheight  ...  enginesize  fuelsystem  \
0         88.6      168.8      64.1       48.8  ...         130           5   
1         88.6      168.8      64.1       48.8  ...         130           5   
2         94.5      171.2      65.5       52.4  ...         152           5   
3         99.8      176.6      66.2       54.3  ...         109           5   
4         99.4      176.6      66.4       54.3  ...         136           5   
..         ...        ...       ...        ...  ...         ...         ...   
200      109.1      188.8      68.9       55.5  ...         141           5   
201      109.1      188.8      68.8       55.5  ...         141           5   
202      109.1      188.8      68.9       55.5  ...         173           5   
203      109.1      188.8      68.9       55.5  ...         145           3   
204      109.1      188.8      68.9       55.5  ...         141           5   

     boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
0         3.47    2.68               9.0         111     5000       21   
1         3.47    2.68               9.0         111     5000       21   
2         2.68    3.47               9.0         154     5000       19   
3         3.19    3.40              10.0         102     5500       24   
4         3.19    3.40               8.0         115     5500       18   
..         ...     ...               ...         ...      ...      ...   
200       3.78    3.15               9.5         114     5400       23   
201       3.78    3.15               8.7         160     5300       19   
202       3.58    2.87               8.8         134     5500       18   
203       3.01    3.40              23.0         106     4800       26   
204       3.78    3.15               9.5         114     5400       19   

     highwaympg    price  
0            27  13495.0  
1            27  16500.0  
2            26  16500.0  
3            30  13950.0  
4            22  17450.0  
..          ...      ...  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0  

[205 rows x 23 columns]

In [30]:
x=df.iloc[:,:22].values
y=df.iloc[:,22].values

In [31]:
x

array([[1.0e+00, 0.0e+00, 1.0e+00, ..., 5.0e+03, 2.1e+01, 2.7e+01],
       [1.0e+00, 0.0e+00, 1.0e+00, ..., 5.0e+03, 2.1e+01, 2.7e+01],
       [1.0e+00, 0.0e+00, 1.0e+00, ..., 5.0e+03, 1.9e+01, 2.6e+01],
       ...,
       [1.0e+00, 0.0e+00, 0.0e+00, ..., 5.5e+03, 1.8e+01, 2.3e+01],
       [0.0e+00, 1.0e+00, 0.0e+00, ..., 4.8e+03, 2.6e+01, 2.7e+01],
       [1.0e+00, 1.0e+00, 0.0e+00, ..., 5.4e+03, 1.9e+01, 2.5e+01]])

In [32]:
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [34]:
x_train.shape

(143, 22)

In [35]:
x_test.shape

(62, 22)

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
model1=LinearRegression()

In [38]:
model1.fit(x_train,y_train)

LinearRegression()

In [39]:
from sklearn.metrics import r2_score

In [40]:
y_pred=model1.predict(x_test)

In [41]:
r2_score(y_test,y_pred)

0.7888731375409521

In [42]:
from sklearn.svm import SVR

In [43]:
model2=SVR()

In [44]:
model2.fit(x_train,y_train)

SVR()

In [45]:
y_pred2=model2.predict(x_test)

In [46]:
r2_score(y_test,y_pred2)

-0.13395771040378035

In [47]:
from sklearn import tree

In [48]:
model3=tree.DecisionTreeRegressor()

In [49]:
model3.fit(x_train,y_train)

DecisionTreeRegressor()

In [50]:
y_pred3=model3.predict(x_test)

In [51]:
r2_score(y_test,y_pred3)

0.8662722720996345

In [52]:
from sklearn.neighbors import KNeighborsRegressor

In [53]:
model4=KNeighborsRegressor()

In [54]:
model4.fit(x_train,y_train)

KNeighborsRegressor()

In [55]:
y_pred4=model4.predict(x_test)

In [56]:
r2_score(y_test,y_pred4)

0.795359161639146